# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructoravailablesections_show_insights_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoravailablesections',
            name='show_discussions_management',
            field=models.BooleanField(default=True, verbose_name=b'Show Discussions Management'),
        ),
    ]
