# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-26 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_instructoravailablesections_show_discussions_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoravailablesections',
            name='show_nw_help',
            field=models.BooleanField(default=True, verbose_name=b'Show "NimblyWise Help Center" section'),
        ),
    ]
