# Generated by Django 2.2.13 on 2020-11-12 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_instructoravailablesections_nw_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructoravailablesections',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='instructor_dashboard_tabs',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Instructor'),
        ),
    ]
