# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0015_organizationtype_enable_page_level_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('last_send_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credo_send_scores',
            },
        ),
        migrations.CreateModel(
            name='SendScoresMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('last_send_time', models.DateTimeField(blank=True, null=True)),
                ('email_scores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credo_modules.SendScores')),
            ],
            options={
                'db_table': 'credo_send_scores_mailing',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sendscores',
            unique_together=set([('user', 'course_id', 'block_id')]),
        ),
    ]
