# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0017_remove_sendscoresmailing_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='enable_extended_progress_page',
            field=models.BooleanField(default=False, verbose_name=b'Enable Extended Progress Page'),
        ),
    ]
