# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0018_organizationtype_enable_extended_progress_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopySectionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(max_length=255)),
                ('source_course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('dst_course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('status', models.CharField(choices=[(b'not_started', b'Not Started'), (b'started', b'Started'), (b'finished', b'Finished'), (b'error', b'Error')], default=b'not_started', max_length=255)),
            ],
            options={
                'db_table': 'copy_section_task',
            },
        ),
        migrations.AlterUniqueTogether(
            name='copysectiontask',
            unique_together=set([('task_id', 'block_id', 'dst_course_id')]),
        ),
    ]
