# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0020_custom_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequentialViewedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('data', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sequential_viewed_task',
            },
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='available_roles',
            field=models.ManyToManyField(blank=True, to='credo_modules.CustomUserRole'),
        ),
    ]
