# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0021_sequential_viewed_task_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'credo_tracking_logs',
            },
        ),
    ]
