# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0022_dblogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexcludeinsights',
            options={'verbose_name': 'item exclude', 'verbose_name_plural': 'items exclude insights'},
        ),
        migrations.AddField(
            model_name='courseexcludeinsights',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
