# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0023_update_course_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='enable_item_analysis_reports',
            field=models.BooleanField(default=False, verbose_name=b'Enable Item Analysis Reports'),
        ),
    ]
