# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0024_organizationtype_enable_item_analysis_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserrole',
            name='edit_library_content',
            field=models.BooleanField(default=True, verbose_name=b'Unit: Can edit library content'),
        ),
    ]
