# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0026_customuserrole_update_library_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUsageLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('block_type', models.CharField(blank=True, max_length=32, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'credo_usage_logs',
            },
        ),
    ]
