# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0027_courseusagelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='exclude_properties',
            field=models.TextField(blank=True, help_text=b'Values should be separated by commas', verbose_name=b'Excluded property names in Insights'),
        ),
    ]
