# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0029_org_default_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, verbose_name=b'Tag name')),
                ('insights_view', models.BooleanField(default=True, verbose_name=b'Display on the Insights')),
                ('progress_view', models.BooleanField(default=True, verbose_name=b'Display on the My Skills page')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credo_modules.Organization')),
            ],
            options={
                'ordering': ('org', 'tag_name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='organizationtag',
            unique_together=set([('org', 'tag_name')]),
        ),
    ]
