# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0029_organization_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTagOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, verbose_name=b'Tag name')),
                ('order_num', models.IntegerField(verbose_name=b'Order num')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credo_modules.Organization')),
            ],
            options={
                'ordering': ('order_num', 'tag_name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='organizationtagorder',
            unique_together=set([('org', 'tag_name')]),
        ),
    ]
