# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0031_organization_tag_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, unique=True, verbose_name=b'Tag name')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
    ]
