# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0032_tagdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='my_skills_page_lti_access',
            field=models.BooleanField(default=False, verbose_name=b'Display LTI link for My Skills/Progress LMS page in Constructor'),
        ),
    ]
