# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0033_org_default_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequentialBlockAnswered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_id', models.CharField(db_index=True, max_length=255)),
                ('first_answered_block_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sequentialblockanswered',
            unique_together=set([('sequential_id', 'user_id')]),
        ),
    ]
