# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0034_sequential_block_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUsageMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=255, unique=True, verbose_name=b'Org')),
                ('updated_ids', models.TextField()),
            ],
        ),
    ]
