# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0035_orgusagemigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WistiaIframeMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_hash', models.CharField(db_index=True, max_length=255)),
                ('wistia_video_url', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('s3_video_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
