# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0037_auto_20200225_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptCourseMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptUserMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
