# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0038_attemptcoursemigration_attemptusermigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
        ),
    ]
