# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-08 21:09
from __future__ import unicode_literals

import credo_modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0039_tracking_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPropertiesPerOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=255, unique=True, verbose_name=b'Org')),
                ('data', models.TextField(help_text=b'Config in JSON format', validators=[credo_modules.models.validate_json_props], verbose_name=b'Registration Properties')),
            ],
            options={
                'db_table': 'credo_registration_properties_v2',
                'verbose_name': 'registration properties item',
                'verbose_name_plural': 'registration properties per org',
            },
        ),
        migrations.AddField(
            model_name='trackinglog',
            name='ora_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
