# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0039_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('org_id', models.CharField(db_index=True, max_length=80)),
                ('course', models.CharField(max_length=255)),
                ('run', models.CharField(max_length=80)),
                ('prop_term', models.CharField(blank=True, max_length=20, null=True)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('is_view', models.BooleanField(default=True)),
                ('answer_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('display_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('question_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_hash', models.CharField(max_length=80, null=True)),
                ('is_ora_block', models.BooleanField(default=False)),
                ('ora_criterion_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.FloatField(null=True)),
                ('max_grade', models.FloatField(null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('correctness', models.CharField(blank=True, max_length=20, null=True)),
                ('is_new_attempt', models.BooleanField(default=False)),
                ('properties_data', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('attempts', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_filename', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLogProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(db_index=True, max_length=255)),
                ('prop_name', models.CharField(max_length=255)),
                ('prop_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='trackinglog',
            index_together=set([('org_id', 'timestamp')]),
        ),
    ]
