# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0040_registration_properties_per_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=255, verbose_name='Org')),
                ('course_id', models.CharField(max_length=255, null=True, verbose_name='Course ID')),
                ('data', models.TextField(help_text='Config in JSON format',
                                          verbose_name='List of available properties')),
                ('update_ts', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trackinglogprop',
            name='prop_name',
        ),
        migrations.RemoveField(
            model_name='trackinglogprop',
            name='prop_value',
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='course_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='org_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='update_ts',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop0',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop8',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop9',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop10',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop11',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop12',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop13',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop14',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop15',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop16',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop17',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop18',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackinglogprop',
            name='prop19',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
