# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0040_auto_20200515_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglog',
            name='is_ora_empty_rubrics',
            field=models.BooleanField(default=False),
        ),
    ]
