# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0042_auto_20200610_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequentialBlockAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('dt', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='propertiesinfo',
            name='org',
            field=models.CharField(db_index=True, max_length=255, verbose_name=b'Org'),
        ),
    ]
