# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0045_auto_20200625_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglog',
            name='update_process_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='update_ts',
            field=models.IntegerField(),
        ),
        migrations.AlterIndexTogether(
            name='trackinglog',
            index_together=set([('org_id', 'ts'), ('user_id', 'sequential_id')]),
        ),
    ]
