# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0046_auto_20200625_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglogprop',
            name='update_process_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
