# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0047_trackinglogprop_update_process_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinglog',
            name='answer_hash',
        ),
        migrations.AddField(
            model_name='trackinglog',
            name='block_tag_id',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
