# Generated by Django 2.2.13 on 2020-10-12 12:51

from django.db import migrations, models
import openedx.core.lib.hash_utils


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0053_enrollment_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdxApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('header_value', models.CharField(default=openedx.core.lib.hash_utils.short_token, max_length=32, unique=True)),
            ],
        ),
    ]
