# Generated by Django 2.2.13 on 2020-10-12 16:13

import credo_modules.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import openedx.core.lib.hash_utils


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0054_edx_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxapitoken',
            name='header_value',
            field=models.CharField(default=openedx.core.lib.hash_utils.short_token, max_length=255, unique=True),
        ),
    ]
