# Generated by Django 2.2.13 on 2020-11-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0057_copy_block_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyblocktask',
            name='task_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
