# Generated by Django 2.2.13 on 2020-12-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0058_auto_20201126_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('hidden', 'Is hidden for all'), ('beta', 'Published only for beta testers'), ('published', 'Published for all')], default='hidden', max_length=20)),
            ],
            options={
                'ordering': ['feature_name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureBetaTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credo_modules.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
