# Generated by Django 2.2.13 on 2020-12-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0059_feature_featurebetatester'),
    ]

    operations = [
        migrations.CreateModel(
            name='OraBlockScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('org_id', models.CharField(db_index=True, max_length=80)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('answer', models.TextField(null=True)),
                ('score_type', models.CharField(choices=[('peer', 'peer'), ('self', 'self'), ('staff', 'staff')], max_length=10)),
                ('criterion', models.CharField(max_length=255)),
                ('option_label', models.CharField(max_length=255, null=True)),
                ('points_possible', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('created', models.DateTimeField(null=True)),
                ('grader_id', models.IntegerField(null=True)),
            ],
        ),
    ]
