# Generated by Django 2.2.13 on 2021-01-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0062_usersettings_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(db_index=True, max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
    ]
