# Generated by Django 2.2.13 on 2021-04-30 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0063_profiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorEvaluationInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('evaluation_block_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
