# Generated by Django 2.2.13 on 2021-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0063_profiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserrole',
            name='course_studio_access',
            field=models.BooleanField(default=True, verbose_name='Course Studio Access'),
        ),
    ]
