# Generated by Django 2.2.13 on 2021-04-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0064_siblingblocknotupdated_siblingblockupdatetask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siblingblocknotupdated',
            options={'verbose_name': 'Cousin Content Block', 'verbose_name_plural': 'Cousin Content Blocks'},
        ),
        migrations.AlterModelOptions(
            name='siblingblockupdatetask',
            options={'verbose_name': 'CMS Push Task', 'verbose_name_plural': 'CMS Push Tasks'},
        ),
        migrations.AddField(
            model_name='siblingblocknotupdated',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siblingblocknotupdated',
            name='source_block_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siblingblocknotupdated',
            name='source_block_parents_path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
