# Generated by Django 2.2.13 on 2021-04-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0064_customuserrole_course_studio_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='default_lti_staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_lti_org_types', to='credo_modules.CustomUserRole', verbose_name='Default LTI Staff Role'),
        ),
    ]
