# Generated by Django 2.2.13 on 2021-05-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0064_supervisorevaluationinvitation'),
        ('credo_modules', '0065_organizationtype_default_lti_staff_role'),
    ]

    operations = [
    ]
