# Generated by Django 2.2.13 on 2021-04-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0065_organizationtype_default_lti_staff_role'),
        ('credo_modules', '0065_siblingblocknotupdated_siblingblockupdatetask_update'),
    ]

    operations = [
    ]
