# Generated by Django 2.2.24 on 2021-07-01 10:59

import common.djangoapps.credo_modules.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credo_modules', '0066_merge_20210506_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingBlockNotUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_course_id', models.CharField(db_index=True, max_length=255)),
                ('source_block_name', models.CharField(max_length=255, null=True)),
                ('source_block_parents_path', models.CharField(max_length=1024, null=True)),
                ('source_block_id', models.CharField(max_length=255)),
                ('sibling_course_id', models.CharField(db_index=True, max_length=255)),
                ('sibling_block_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('source_version_published_date', models.DateTimeField(null=True)),
                ('source_version_publisher_user_id', models.IntegerField(null=True)),
                ('sibling_version_published_date', models.DateTimeField(null=True)),
                ('sibling_version_publisher_user_id', models.IntegerField(null=True)),
                ('ignore', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cousin Content Block',
                'verbose_name_plural': 'Cousin Content Blocks',
            },
        ),
        migrations.CreateModel(
            name='SiblingBlockUpdateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('finished', 'Finished'), ('error', 'Error')], default='not_started', max_length=255)),
                ('source_course_id', models.CharField(db_index=True, max_length=255)),
                ('source_block_id', models.CharField(max_length=255)),
                ('sibling_course_id', models.CharField(db_index=True, max_length=255)),
                ('sibling_block_id', models.CharField(max_length=255, null=True)),
                ('published', models.BooleanField(default=False)),
                ('sibling_block_prev_version', models.CharField(max_length=255, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CMS Push Task',
                'verbose_name_plural': 'CMS Push Tasks',
            },
            bases=(common.djangoapps.credo_modules.models.TaskStatusMixin, models.Model),
        ),
    ]
