# Generated by Django 2.2.13 on 2021-05-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0064_supervisorevaluationinvitation'),
        ('credo_modules', '0066_merge_20210407_1355'),
    ]

    operations = [
    ]
