# Generated by Django 2.2.13 on 2021-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0067_merge_20210507_1501'),
        ('credo_modules', '0066_merge_20210506_1120'),
    ]

    operations = [
    ]
