# Generated by Django 2.2.24 on 2021-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0067_siblingblocknotupdated_siblingblockupdatetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('celery_task_id', models.CharField(max_length=255)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_params', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('countdown', models.IntegerField(default=0)),
                ('attempt_num', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('processed', 'Processed')], default='created', max_length=32)),
                ('result', models.CharField(choices=[('unknown', 'Unknown'), ('success', 'Success'), ('failure', 'Failure')], default='unknown', max_length=32)),
                ('prev_attempt_err_msg', models.TextField(blank=True, null=True)),
                ('course_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('assignment_id', models.IntegerField(db_index=True, null=True)),
                ('created', models.DateTimeField(db_index=True, auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
