# Generated by Django 2.2.24 on 2021-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0068_delayedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRedirectAllowedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['host'],
            },
        ),
    ]
