# Generated by Django 2.2.24 on 2021-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0069_loginredirectallowedhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginredirectallowedhost',
            name='require_https',
            field=models.BooleanField(default=True),
        ),
    ]
