# Generated by Django 2.2.24 on 2021-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0070_loginredirectallowedhost_require_https'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorevaluationinvitation',
            name='profile_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
