# Generated by Django 2.2.24 on 2021-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0071_supervisorevaluationinvitation_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorevaluationinvitation',
            name='survey_finished',
            field=models.BooleanField(default=False),
        ),
    ]
