# Generated by Django 2.2.24 on 2021-10-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0072_supervisorevaluationinvitation_survey_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorevaluationinvitation',
            name='supervisor_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
