# Generated by Django 2.2.24 on 2021-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0073_supervisorevaluationinvitation_supervisor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglog',
            name='ora_status',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
