# Generated by Django 2.2.24 on 2021-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0074_trackinglog_ora_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='enable_badgr_integration',
            field=models.BooleanField(default=False, verbose_name='Badgr Integration'),
        ),
    ]
