# Generated by Django 3.2.13 on 2022-05-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0075_organizationtype_enable_badgr_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtype',
            name='enable_new_carousel_view',
        ),
    ]
