# Generated by Django 3.2.13 on 2023-03-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0076_remove_organizationtype_enable_new_carousel_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserrole',
            name='rerun_course',
            field=models.BooleanField(default=False, verbose_name='Rerun Course'),
        ),
    ]
