# Generated by Django 3.2.19 on 2023-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0077_customuserrole_rerun_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrgToRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_index=True, max_length=255)),
                ('org_id', models.CharField(max_length=255)),
            ],
        ),
    ]
