# Generated by Django 3.2.19 on 2023-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo_modules', '0078_coursetoremove_orgtoremove'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetoremove',
            name='mongo_data_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursetoremove',
            name='mysql_data_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursetoremove',
            name='vertica_data_removed',
            field=models.BooleanField(default=False),
        ),
    ]
