# Generated by Django 2.2.13 on 2020-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0001_squashed_0026_auto_20200401_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLConfigurationPerMicrosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Microsite Domain Name')),
                ('entity_id', models.CharField(default='http://saml.example.com', max_length=255, verbose_name='Entity ID')),
                ('org_info_str', models.TextField(default='{"en-US": {"url": "http://www.example.com", "displayname": "Example Inc.", "name": "example"}}', help_text="JSON dictionary of 'url', 'displayname', and 'name' for each language", verbose_name='Organization Info')),
                ('other_config_str', models.TextField(default='{\n"SECURITY_CONFIG": {"metadataCacheDuration": 604800, "signMetadata": false}\n}', help_text='JSON object defining advanced settings that are passed on to python-saml. Valid keys that can be set here include: SECURITY_CONFIG and SP_EXTRA')),
            ],
            options={
                'verbose_name_plural': 'SAML Configuration per Microsite',
                'verbose_name': 'SAML Configuration per Microsite',
            },
        ),
        migrations.AddField(
            model_name='samlconfiguration',
            name='separate_settings_per_microsite',
            field=models.BooleanField(default=False, verbose_name='Separate Settings per Microsite'),
        ),
    ]
