# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microsite_configuration', '0003_delete_historical_records'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsite',
            options={'ordering': ('key',)},
        ),
        migrations.AlterModelOptions(
            name='micrositeorganizationmapping',
            options={'ordering': ('organization', 'microsite')},
        ),
        migrations.AlterField(
            model_name='microsite',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microsite', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='micrositehistory',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='micrositeorganizationmapping',
            name='organization',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='micrositeorganizationmapping',
            unique_together=set([('organization', 'microsite')]),
        ),
    ]
