# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_provider', '0006_lticontextid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignmentlock',
            name='lti_version',
            field=models.CharField(choices=[(b'1.1', b'LTI 1.1'), (b'1.3', b'LTI 1.3')], default=b'1.1', max_length=10),
        ),
        migrations.AddField(
            model_name='lticontextid',
            name='lti_version',
            field=models.CharField(choices=[(b'1.1', b'LTI 1.1'), (b'1.3', b'LTI 1.3')], default=b'1.1', max_length=10),
        ),
        migrations.AlterField(
            model_name='gradedassignmentlock',
            name='graded_assignment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='gradedassignmentlock',
            unique_together=set([('graded_assignment_id', 'lti_version')]),
        ),
    ]
