# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti_provider', '0007_auto_20190815_0623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lticontextid',
            unique_together=set([('course_key', 'usage_key', 'user', 'lti_version')]),
        ),
    ]
