# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_provider', '0010_lticontextid_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
