# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0004_blockstructuremodel_usagekeywithrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCourseStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('block_type', models.CharField(max_length=255)),
                ('parent_id', models.CharField(max_length=255, null=True)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('graded', models.SmallIntegerField()),
                ('section_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_course_structure',
            },
        ),
        migrations.CreateModel(
            name='ApiCourseStructureLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_course_structure_lock',
            },
        ),
        migrations.RunSQL(
            "CREATE TABLE `api_course_structure_tags` (" +
            "`id` int(11) NOT NULL AUTO_INCREMENT," +
            "`course_id` varchar(255) NOT NULL," +
            "`rubric` varchar(255) DEFAULT NULL," +
            "`tag_name` varchar(255) NOT NULL," +
            "`tag_value` varchar(255) NOT NULL," +
            "`block_id` varchar(255) NOT NULL," +
            "PRIMARY KEY (`id`)," +
            "KEY `api_course_structure_block_id_f54c31ba_fk_api_cours` (`block_id`)," +
            "KEY `api_course_structure_tags_course_id_474f4c0c` (`course_id`)," +
            "KEY `api_course_structure_tags_tag_value_65d2ae95` (`tag_value`)," +
            "CONSTRAINT `api_course_structure_block_id_f54c31ba_fk_api_cours` FOREIGN KEY (`block_id`) REFERENCES `api_course_structure` (`block_id`)" +
            ") ENGINE=InnoDB DEFAULT CHARSET=utf8"
        ),
        migrations.CreateModel(
            name='BlockToSequential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_name', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('graded', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'block_to_sequential',
            },
        ),
    ]
