# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0004_blockstructuremodel_usagekeywithrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCourseStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('block_type', models.CharField(max_length=255)),
                ('parent_id', models.CharField(max_length=255, null=True)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('graded', models.SmallIntegerField()),
                ('section_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_course_structure',
            },
        ),
        migrations.CreateModel(
            name='ApiCourseStructureLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_course_structure_lock',
            },
        ),
        migrations.CreateModel(
            name='ApiCourseStructureTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('rubric', models.CharField(help_text=b'Should be filled in only for ORA blocks', max_length=255, null=True)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_value', models.CharField(db_index=True, max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block_structure.ApiCourseStructure', to_field=b'block_id')),
            ],
            options={
                'db_table': 'api_course_structure_tags',
            },
        ),
        migrations.CreateModel(
            name='BlockToSequential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_id', models.CharField(db_index=True, max_length=255)),
                ('sequential_name', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('graded', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'block_to_sequential',
            },
        ),
    ]
