# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0005_apicoursestructure_apicoursestructurelock_apicoursestructuretags_blocktosequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicoursestructure',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blocktosequential',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
