# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0006_auto_20191217_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAuthProfileFieldsCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_auth_profile_fields_cache',
            },
        ),
    ]
