# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-02 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0007_courseauthprofilefieldscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktosequential',
            name='visible_to_staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
