# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0008_blocktosequential_visible_to_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicoursestructuretags',
            name='is_parent',
            field=models.SmallIntegerField(default=0),
        ),
    ]
