# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0009_apicoursestructuretags_is_parent'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_course_structure_tags ADD COLUMN `ts` int(11) DEFAULT NULL"
        )
    ]
