# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0010_apicoursestructuretags_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCourseStructureUpdateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_course_structure_update_time',
            },
        ),
    ]
