# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-21 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0013_apicoursestructuretags_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicoursestructuretags',
            name='root_tag_value_hash',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
