# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-21 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0013_apicoursestructuretags_org_id'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_course_structure_tags ADD COLUMN `root_tag_value_hash` varchar(80) DEFAULT NULL"
        )
    ]
