# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0014_apicoursestructuretags_root_tag_value_hash'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX api_course_structure_tags_org_id_61798263 ON api_course_structure_tags(org_id)"
        ),
        migrations.RunSQL(
            "CREATE INDEX api_course_structure_tags_ts_0fa12740 ON api_course_structure_tags(ts)"
        )
    ]
