# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0014_apicoursestructuretags_root_tag_value_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicoursestructuretags',
            name='ts',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
