# Generated by Django 2.2.13 on 2020-11-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0015_auto_20200724_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicoursestructuretags',
            options={'managed': False},
        ),
    ]
