# Generated by Django 2.2.13 on 2020-12-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0016_auto_20201112_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='OraBlockStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('org_id', models.CharField(db_index=True, max_length=80)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('is_ora_empty_rubrics', models.BooleanField(default=False)),
                ('support_multiple_rubrics', models.BooleanField(default=False)),
                ('is_additional_rubric', models.BooleanField(default=False)),
                ('prompt', models.TextField(null=True)),
                ('rubric_criteria', models.TextField(null=True)),
                ('display_rubric_step_to_students', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ora_block_structure',
            },
        ),
    ]
