# Generated by Django 2.2.13 on 2020-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0017_orablockstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='orablockstructure',
            name='steps',
            field=models.TextField(null=True),
        ),
    ]
