# Generated by Django 2.2.13 on 2020-12-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0018_orablockstructure_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='orablockstructure',
            name='ungraded',
            field=models.BooleanField(default=False),
        ),
    ]
