# Generated by Django 2.2.24 on 2021-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0020_trim_leading_slashes_in_data_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('hash_id', models.CharField(db_index=True, max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=None, null=True)),
                ('created_time', models.DateTimeField(default=None, null=True)),
                ('updated_by', models.IntegerField(default=None, null=True)),
                ('updated_time', models.DateTimeField(default=None, null=True)),
                ('created_as_copy', models.BooleanField(default=False)),
                ('published_after_copy', models.BooleanField(default=False)),
                ('reverted_to_previous_version', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_block_info',
                'unique_together': {('course_id', 'block_id')},
            },
        ),
    ]
