# Generated by Django 2.2.13 on 2021-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0020_apiblockinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiblockinfo',
            name='created_as_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiblockinfo',
            name='published_after_copy',
            field=models.BooleanField(default=False),
        ),
    ]
