# Generated by Django 2.2.13 on 2021-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0021_apiblockinfo_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiblockinfo',
            name='reverted_to_previous_version',
            field=models.BooleanField(default=False),
        ),
    ]
