# Generated by Django 2.2.24 on 2021-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0021_apiblockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFieldsCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255, unique=True)),
                ('additional_profile_fields', models.TextField(blank=True, null=True)),
                ('enable_subsection_gating', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'course_fields_cache',
            },
        ),
    ]
