# Generated by Django 2.2.24 on 2021-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0022_coursefieldscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_block_cache',
                'unique_together': {('block_id', 'field_name')},
                'index_together': {('field_name', 'field_value')},
            },
        ),
    ]
