# Generated by Django 2.2.24 on 2021-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0023_blockcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicoursestructurelock',
            name='published_on',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apicoursestructurelock',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
