# Generated by Django 2.2.24 on 2021-12-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0024_auto_20211214_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicoursestructurelock',
            name='course_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
