# Generated by Django 2.2.24 on 2021-12-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0025_auto_20211216_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBlockInfoVersionsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('version_id', models.CharField(max_length=255)),
                ('siblings_hash_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_block_info_versions_history',
            },
        ),
        migrations.AddField(
            model_name='apiblockinfo',
            name='current_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiblockinfo',
            name='previous_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
