# Generated by Django 2.2.24 on 2022-01-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0026_api_block_info_versions_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBlockInfoNotSiblings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_block_id', models.CharField(db_index=True, max_length=255)),
                ('dst_block_id', models.CharField(db_index=True, max_length=255)),
                ('source_block_version', models.CharField(max_length=255, null=True)),
                ('dst_block_version', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'api_block_info_not_siblings',
            },
        ),
    ]
