# Generated by Django 2.2.24 on 2022-02-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0027_apiblockinfonotsiblings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiblockinfo',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='apiblockinfo',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='apiblockinfonotsiblings',
            name='dst_block_version',
        ),
        migrations.RemoveField(
            model_name='apiblockinfonotsiblings',
            name='source_block_version',
        ),
        migrations.AddField(
            model_name='apiblockinfo',
            name='created_as_copy_from_course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiblockinfo',
            name='published_content_version',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
