# Generated by Django 2.2.24 on 2022-04-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0028_auto_20220206_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiblockinfonotsiblings',
            name='dst_course_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiblockinfonotsiblings',
            name='source_course_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
