# Generated by Django 3.2.13 on 2022-05-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0029_auto_20220427_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiblockinfonotsiblings',
            options={'verbose_name': 'Cousin Content Block', 'verbose_name_plural': 'Cousin Content Blocks'},
        ),
    ]
