# Generated by Django 2.2.24 on 2021-11-18 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activity')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='External Entity ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activity')),
                ('description', models.TextField(default=None, null=True, verbose_name='Description')),
                ('url', models.CharField(max_length=255, verbose_name='External URL')),
                ('image_url', models.CharField(max_length=255, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='External Entity ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activity')),
                ('description', models.TextField(default=None, null=True, verbose_name='Description')),
                ('criteria_narrative', models.TextField(default=None, null=True, verbose_name='Criteria Narrative')),
                ('url', models.CharField(max_length=255, verbose_name='External URL')),
                ('image_url', models.CharField(max_length=255, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badgr_integration.Issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='External id')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badgr_integration.Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
