# Generated by Django 2.2.24 on 2021-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgr_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertion',
            name='image_url',
            field=models.CharField(max_length=255, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assertion',
            name='url',
            field=models.CharField(max_length=255, verbose_name='External URL'),
            preserve_default=False,
        ),
    ]
