# Generated by Django 3.2.13 on 2022-05-11 08:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('badgr_integration', '0002_assertion_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
