# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_auto_20161004_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategories',
            name='org_type',
            field=models.IntegerField(null=True, verbose_name='Applicable for organization type'),
        ),
        migrations.AlterField(
            model_name='tagavailablevalues',
            name='value',
            field=models.CharField(help_text=b'Limited to 255 symbols', max_length=255),
        ),
    ]
