# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-21 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_auto_20191002_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagOrgTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.IntegerField(verbose_name='Applicable for organization type')),
            ],
        ),
        migrations.RemoveField(
            model_name='tagcategories',
            name='org_type',
        ),
        migrations.AddField(
            model_name='tagorgtypes',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagging.TagCategories'),
        ),
    ]
