# Generated by Django 2.2.13 on 2021-03-23 15:24

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0005_auto_20191021_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategories',
            name='disable_superusers_tags',
            field=models.BooleanField(
                default=False, verbose_name='Prohibit users from removing outcomes added by super users'),
        ),
    ]
