# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0006_course_mode_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEmailSite',
            fields=[
                ('course_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_from_site', serialize=False, to='bulk_email.CourseEmail')),
                ('site_id', models.IntegerField()),
            ],
        ),
    ]
