# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='allow_to_add_instructors_via_lti',
            field=models.NullBooleanField(help_text=b"Automatically adds instructor role to the user who came through the LTI if some of these parameters: 'Administrator', 'Instructor', 'Staff' was passed. Choose 'Yes' to enable this feature. "),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='issuer',
            field=models.CharField(help_text="This will usually look something like 'http://example.com'. Value provided by LTI 1.3 Platform", max_length=255, unique=True),
        ),
    ]
