# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0002_auto_20190822_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='use_names_and_role_provisioning_service',
            field=models.BooleanField(default=False, help_text='Use LTI 1.3 advantage names and role provisioning service to get first name/last name/email about student (not recommended for usage because of performance reasons, may be needed for LTI 1.3 certification)'),
        ),
    ]
