# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0003_ltitool_use_names_and_role_provisioning_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
