# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0004_gradedassignment_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='auth_audience',
            field=models.CharField(blank=True, help_text="The platform's OAuth2 Audience (aud). Usually could be skipped", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='issuer',
            field=models.CharField(help_text="This will usually look something like 'http://example.com'. Value provided by LTI 1.3 Platform", max_length=255),
        ),
    ]
