# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0005_auto_20200430_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='use_by_default',
            field=models.BooleanField(default=False, help_text='This iss config will be used in case if client-id was not passed'),
        ),
        migrations.AlterUniqueTogether(
            name='ltitool',
            unique_together=set([('issuer', 'client_id')]),
        ),
    ]
