# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-01 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0006_auto_20200430_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ltitool',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
