# Generated by Django 2.2.24 on 2022-04-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0007_auto_20200501_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiExternalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_course_id', models.CharField(db_index=True, max_length=255)),
                ('edx_course_id', models.CharField(db_index=True, max_length=255)),
                ('context_memberships_url', models.TextField(blank=True, null=True)),
                ('users_last_sync_date', models.DateTimeField(editable=False, null=True)),
                ('lti_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti1p3_tool.LtiTool')),
            ],
            options={
                'unique_together': {('external_course_id', 'edx_course_id')},
            },
        ),
        migrations.CreateModel(
            name='LtiUserEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti1p3_tool.LtiExternalCourse')),
                ('lti_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti1p3_tool.LtiUser')),
            ],
            options={
                'unique_together': {('lti_user', 'external_course')},
            },
        ),
    ]
