# Generated by Django 2.2.24 on 2022-04-22 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0008_ltiexternalcourse_ltiuserenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiuserenrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
