# Generated by Django 2.2.24 on 2022-04-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0009_ltiuserenrollment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiuserenrollment',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
