# Generated by Django 2.2.24 on 2022-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0010_ltiuserenrollment_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='automatically_unenroll_users',
            field=models.BooleanField(default=False, help_text='Automatically unenroll users using information from the Names and Role Provisioning service.'),
        ),
    ]
