# Generated by Django 3.2.13 on 2022-12-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0012_ltitool_automatically_enroll_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='deep_linking_short_launch_urls',
            field=models.BooleanField(default=False, help_text='Use short launch URLs as the result of deep links embedding. Pass block_id in LTI custom params'),
        ),
    ]
