# Generated by Django 3.2.19 on 2023-07-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti1p3_tool', '0013_ltitool_deep_linking_short_launch_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='edx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti1p3_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ltitool',
            name='lti_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti1p3_tool.ltiplatform'),
        ),
    ]
