# Generated by Django 3.2.19 on 2023-08-17 17:32

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0014_auto_20230710_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiDeepLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('lti_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti1p3_tool.ltitool')),
            ],
        ),
        migrations.CreateModel(
            name='LtiDeepLinkCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('lti_deep_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti1p3_tool.ltideeplink')),
            ],
        ),
    ]
