# Generated by Django 3.2.19 on 2023-08-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool', '0015_ltideeplink_ltideeplinkcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ltideeplink',
            unique_together={('lti_tool', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='ltideeplinkcourse',
            unique_together={('lti_deep_link', 'course_key')},
        ),
    ]
